unbind C-b
set -g prefix C-k
bind k last-window
bind C-k send-prefix

set -g mouse on

bind r source-file ~/.config/tmux.conf \; display "Configuration reloaded."
set-option -g history-limit 5000

# mark the current pane with Prefix + m and jump back to it using prefix + backtick
bind \` switch-client -t '{marked}'
# to unmark a pane, press prefix + m on the marked pane, or prefix + M anywhere

# see line 12, prefix + k (i.e., ctrl + k + k) jumps to prev. win.
bind-key -n C-PageDown next-window
bind-key -n C-PageUp previous-window

set -g default-terminal "screen-256color"
set -g status-position top

# Set default status bar style (white text on black background)
set -g status-style bg=black,fg=white

# Set style for inactive windows (normal font)
set-window-option -g window-status-style fg=white,bg=black,nobold

# Set style for the current active window (black text on white background, bold font)
set-window-option -g window-status-current-style fg=black,bg=white,bold

# Set style for the last active window (white text on grey background, bold font)
set-window-option -g window-status-last-style fg=white,bg=colour240,bold

# Explicitly set the format for all windows
set-window-option -g window-status-format "#I:#W#F"
set-window-option -g window-status-current-format "#[fg=black,bg=white,bold]#I:#W#F"


